### ISSUE TITLE
Decreasing expandLevel does not update the component.

### ISSUE THREAD

**Issue by vicaba** [storybookjs/react-inspector#16]
Hi,

I have an input to perform changes in the expandLevel, when increasing the number of expandLevel all goes ok and the changes are reflected in the react-inspector component but when I decrease the expandLevel it doesn't work, the component doesn't decrease its expand level. I'm almost new to react but as far as I know and logically, if I increase the expandLevel and it works, when decreasing it it should work too, right?

**Comment by xyc** [comment]
Hi,

Sorry for taking long to get back. Should be fixed in the next minor v

**Comment by vicaba** [comment]
Thank you.

**Comment by xyc** [comment]
In the meantime https://github.com/xyc/react-object-inspector should be free of this.

**Comment by ndelangen** [comment]
I'm guessing this is completed?

**Comment by alvaro1728** [comment]
This is still broken but I worked around it by temporarily dismounting the component and then remounting it with the lower expandLevel.   So something like this:

```
  render() {
    const {expandLevel = 4} = this.state;
    return (          
          ...
          {expandLevel && <Inspector data={diagnostics} expandLevel={expandLevel} />}
          ...
    );
```

So my onExpand handler looks like this:

```
  onExpand = expandLevel => {
    if (expandLevel < this.state.expandLevel) {
      this.setState({expandLevel: 0}, () => this.setState({expandLevel}));
    } else {
      this.setState({expandLevel});
    }
  }
```
Cheers,
Alvaro
